### ISSUE TITLE
Support Language Preview Features

### ISSUE THREAD

**Issue by brunoborges** [maxandersen/jbang#31]
This tool is a good way to learn new language features that are in preview.

Allow user to `--enable-preview` features in the JDK.

**Comment by maxandersen** [comment]
Yes. Plan is to expose that by allowing setting flags like:

//JAVA_OPTS —enable-preview
//JAVAC_OPTS —enable-preview

This flag is though special compared to otbers as needed on both compile and java step so maybe better to have explict flag foe it. 

Same goes if you want to declare java modules
