### ISSUE TITLE
warn users if javac version is higher than java

### ISSUE THREAD

**Issue by maxandersen** [maxandersen/jbang#50]
[some users](https://twitter.com/mojavelinux/status/1225945104700936192) might have a setup where java is of a lower version than javac meaning they will get a classfile major version error.

We could run java -version / javac -version and just check that java numbers are same or bigger than javac

**Comment by AtharvaThorve** [comment]
I have forked and cloned the repository and I wanted to know a little more about this issue like when should the user be warned about the issue mentioned here

**Comment by maxandersen** [comment]
when we do a build we are anyway spending some seconds to run a build so in the background (to not slow things down) we could run the check.

And just print out that warning if/when mismatch is found.

**Comment by AtharvaThorve** [comment]
after writing my code and running ./gradlew build install i am getting error in spotlessJava 
so i ran gradle spotlessApply but it gives an error stating 'Only Project build scripts can contain plugins {} blocks'

Need some help resolving this issue.

**Comment by maxandersen** [comment]
are you using the gradle wrapper ? i.e. ./gradlew instead of gradle ?  if not then it could be you are picking up older version of gradle ?

**Comment by AtharvaThorve** [comment]
I know this is a dumb doubt but i successfully built the gradle but whatever changes i have made are not being executed whenever i run a program using jbang.
I've been working on it for past couple of hours...need some guidance here

**Comment by maxandersen** [comment]
Do you have the right jbang in your path ? If using locally built one you need the one in build/install folder

**Comment by AtharvaThorve** [comment]
I installed it using sdkman[linux ubuntu].
Its path is /home/atharva/.sdkman/candidates/jbang/current/bin/jbang

**Comment by AtharvaThorve** [comment]
I have created a new pull request which is working fine on my local pc but failed the test...what to do next?

**Comment by maxandersen** [comment]
lets discuss on #50

**Comment by maxandersen** [comment]
closing as complexity not worth the gain.
