### ISSUE TITLE
Support passing VM properties with `-Dx=y`

### ISSUE THREAD

**Issue by remkop** [maxandersen/jbang#68]
From #51: I tried switching on picocli's built-in [debug tracing](https://picocli.info/#_tracing). I ended up changing the source code of the `tz` main method to do this, because I could not figure out how to pass `-Dpicocli.trace=DEBUG` on the command line. I tried these:

```
remko@LAPTOP-7EO0MTL0:/mnt/c/Users/remko/IdeaProjects/jbang$ jbang -Dpicocli.trace=DEBUG examples/tz.java 15:00
Unknown option: '-Dpicocli.trace=DEBUG'
Usage: jbang [-eh] [--verbose] [--version] [--clear-cache] [--completion]
...
```

and

```
remko@LAPTOP-7EO0MTL0:/mnt/c/Users/remko/IdeaProjects/jbang$ jbang examples/tz.java -Dpicocli.trace=DEBUG 15:00
Unknown option: '-Dpicocli.trace=DEBUG'
```

In both cases, picocli is parsing the option and treats it as an application option: first of the jbang application, and next of the tz application. It may be worth treating  `-Dx=y` options to `jbang` as special and pass them as VM parameters.

----

Note that options between the `jbang` command and the script name  should be treated as VM args:

```
jbang -Dx=y script [options]
```

While options after the script name  should be treated as arguments for the script, just like any other option  (not a VM parameter):

```
jbang script  -Dx=y
```

**Comment by maxandersen** [comment]
Was about to say I already did this last night but then realised I hadn't tested for the case of -D coming after script....

Any easy way in picocli to have it not parse them?

**Comment by remkop** [comment]
I didn’t see a ticket so I raised this one.  :-)

When `-Dx=y` is specified after the script, it _should_ be passed to picocli. That gives applications the chance to define their own `-D` option. Sorry I was unclear.

**Comment by maxandersen** [comment]
It was all clear - what I'm struggling with is how to tell picocli to ignore `-D` after the script argument.

i.e.

`jbang -Dfoo=bar myapp.java -Dbaz=boos`

picocli reads all '-D''s where I want it to only pick it up the first one.

I have:

```
@Option(names = { "-D" }, description = "set a system property")
Map<String, String> properties = new HashMap<>();

@Parameters(index = "1..*", arity = "0..*", description = "Parameters to pass on to the script")
	List<String> userParams = new ArrayList<String>();
```

but it is not honoring the userParams and picks up -Dbaz=boos as a property not userParams.

**Comment by remkop** [comment]
Ah, I did not get that, thanks for the clarification!

One idea is to tell picocli to stop looking for options when it sees the first positional parameter: https://picocli.info/#_stop_at_positional

From your example that may be exactly what you are looking for.

**Comment by maxandersen** [comment]
I already have that set to true .... this is all in master.

let me see if i can trace it out.

**Comment by maxandersen** [comment]
ah - my tests didn't get that setting applied - i think it might already just be working....verifying.

**Comment by remkop** [comment]
I was looking at your master and just saw you already apply that... I was about to test what was going on :-) 
Let me know if there is still an issue and I will take a deep(er) dive.

**Comment by maxandersen** [comment]
it works - just the testsuite that wasn't setup properly! closing this as fully fixed then :)

**Comment by remkop** [comment]
Great!
That's a good feature to have. :muscle:  Don't forget to advertise it!  :grin:
