### ISSUE TITLE
Option to prevent access of remote repositories

### ISSUE THREAD

**Issue by dmlloyd** [maxandersen/jbang#80]
Maybe there's a clever way to do this with Maven settings, but it would be nice (for me) to be able to tell jbang not to try to access remote repositories and just fail fast instead of the artifacts are not local.

**Comment by maxandersen** [comment]
you mean like a --offline mode ?

**Comment by maxandersen** [comment]
release 0.21 (being pushed at the moment) now have `--offline` / `-o` support

**Comment by dmlloyd** [comment]
Thanks!
