### ISSUE TITLE
Files.createSymbolicLink() not working on Windows

### ISSUE THREAD

**Issue by dem2k** [maxandersen/jbang#84]
On Wondows when running `jbang.bat -e helloworld.java` it fail with

```
java.nio.file.FileSystemException
  at java.nio.file.Files.createSymbolicLink(Unknown Source)    
  at dk.xam.jbang.Main.createProjectForEdit(Main.java:459)     
```
i suggest to use  **java.nio.file.Files.createLink** method depends on **$os.name** if starts with "**Windows**"

**Comment by maxandersen** [comment]
this was fixed and released via #85
