### ISSUE TITLE
jbang shell script has issues with quoting

### ISSUE THREAD

**Issue by maxandersen** [maxandersen/jbang#87]
as discussed and found in https://github.com/remkop/picocli/issues/998 there are a problem of how quotes are handled by jbang shell script.

I'm not sure if we can actually work around this as the quotes are stripped out before pass to the script hence why we today have "'s around $@ but it seems to not be enough.

**Comment by remkop** [comment]
Looking at this line:

```
eval "exec $(${JAVA_EXEC} ${JBANG_JAVA_OPTIONS} -classpath ${jarPath} dk.xam.jbang.Main "$@")"
```

It looks like the `eval` works on the concatenation of 3 strings:
1. `"exec $(${JAVA_EXEC} ${JBANG_JAVA_OPTIONS} -classpath ${jarPath} dk.xam.jbang.Main "`
2. the expansion of `$@`
3. `")"`

If the expansion of `$@` contains pipe characters, perhaps these are actually not quoted!

I wonder if the following would still have the same problem?

```
ARGS="$@"
eval "exec $(${JAVA_EXEC} ${JBANG_JAVA_OPTIONS} -classpath ${jarPath} dk.xam.jbang.Main ${ARGS})"
```

or, since we are calling `eval`, perhaps this:

```
ARGS="\"$@\""
eval ...
```

**Comment by maxandersen** [comment]
worth a try - i'm sure it will break some other edge case though :)

**Comment by remkop** [comment]
I'm curious: did it make a difference?

**Comment by maxandersen** [comment]
didn't get to try it yet - on my list ;)

**Comment by maxandersen** [comment]
tried it, didn't change anything afaics: https://github.com/maxandersen/jbang/tree/alternativequoting

**Comment by remkop** [comment]
Hey, I just noticed your nice new logo! :heart_eyes:

Ok, thanks for trying. I will experiment a bit more later.

**Comment by maxandersen** [comment]
I think I might solved it, try using https://github.com/maxandersen/jbang/tree/alternativequoting

Basically using printf over echo which seem to retain quotes.

thanks for comments the logo 👍

**Comment by maxandersen** [comment]
one caveat is that with this fix then the following no longer behaves the same:

`jbang helloworld.java "JSH!"`

before would print out "JSH!"

but now it gets passed on as "JSH\!" so in a shell it enters into `dquote>' mode and fails the itest we have.

**Comment by remkop** [comment]
> but now it gets passed on as "JSH\!" so in a shell it enters into `dquote>' mode 

`dquote>` mode is where the shell is waiting for the closing double quote, right? That is strange, how can that happen, if only the exclamation mark is escaped? I would expect it to print:

```
Hello JSH\!
```

That is what happens when I run `echo`:

```
$ echo $(printf "%q" "hello!")
hello\!
```

**Comment by maxandersen** [comment]
well try it :)

anyway - by using this printf then alters the quoting semantics so its no longer natural.

Thus I'm rolling back the proposed change but include some more quote tests so actually will notice if break it in future ;)

**Comment by remkop** [comment]
ok, well, `printf` was a bit of a shorter way of looping over the arguments and quoting each argument in the shell script before invoking `java`. 

If `printf` has the drawback that it escapes unprintable characters, and this introduces undesirable behaviour, then we cannot use it.

Perhaps an alternative is to manually build up the contents of the `ARGS` variable by looping over `$@` and quoting each element?

**Comment by remkop** [comment]
I made a simple program that just prints the args:

```java
public class Main {
    public static void main(String[] args) {
        for (int i = 0; i < args.length; i++) {
            String s = args[i];
            System.out.printf("%d: '%d'%n", s);
        }
    }
}
```

Then made this wrapper script:

```bash
#!/usr/bin/env bash

absolute_path() {
    # if the given path to the jbang launcher is absolute (i.e. it is either starting with / or a
    # 'letter:/' when using gitbash on windows) it is returned unchanged, otherwise we construct an absolute path
    [[ $1 = /* ]] || [[ $1 =~ ^[A-z]:/ ]] && echo "$1" || echo "$PWD/${1#./}"
}

resolve_symlink() {
    if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
    sym_resolved=$(readlink ${minusFarg} $1)

    if [[ -n $sym_resolved ]]; then
        echo $sym_resolved
    else
        echo $1
    fi
}

TMPPATH=$(resolve_symlink $(absolute_path $0))
echo $TMPPATH
JARPATH=$(dirname $TMPPATH)
echo $JARPATH

JAVA_EXE=/usr/lib/jvm/graalvm/bin/java
ARGS=$(printf "%q " "$@")

echo "running plain..."
${JAVA_EXE} -cp $JARPATH Main "$@"

echo "running args..."
$JAVA_EXE -cp $JARPATH Main ${ARGS}

echo "running eval plain..."
eval "exec $(${JAVA_EXE} -cp $JARPATH Main "$@")"

echo "running eval args..."
eval "exec $($JAVA_EXE -cp $JARPATH Main ${ARGS})"
```

Given this input:

```
./wrapper.sh "a|b c!" c d
```

I get the following output:

```
/mnt/c/Users/remko/source/wrapper.sh
/mnt/c/Users/remko/source
running plain...
0: 'a|b c!'
1: 'c'
2: 'd'
running args...
0: 'a\|b\'
1: 'c\!'
2: 'c'
3: 'd'
running eval plain...
./wrapper.sh: line 35: exec: 0:: not found
```

One observation is that for some reason the `eval "exec $(java...` bit does not work.
But why is it needed? Why not simply use `${JAVA_EXE} -cp $JARPATH Main "$@"` in the `jbang` wrapper script? That seems to have no issue with quoted arguments, including pipes or exclamation marks.

**Comment by maxandersen** [comment]
`$(java...` is what calls out to jbang and generates the actual command to run after it has fetched dependencies, compile the class, built the jar.

That output is then 'eval''ed ..if we don't do it this way we would have to run two java processes and you would not get proper signal/exit code handling.

**Comment by remkop** [comment]
I see... Thanks for the clarification.

**Comment by maxandersen** [comment]
thinking about it might be we should  change how the generated command looks like ...if adding quotes to anything with a set of special characters (" !|;:.*") would help....?
