### ISSUE TITLE
Provide jbang as GH Action

### ISSUE THREAD

**Issue by rsvoboda** [maxandersen/jbang#89]
Provide jbang as GH Action

Right now users have to install jbang on their own if they are using GH Actions.

Install step similar to JDK installation could make use of jbang easier and more transparent
https://github.com/quarkusio/quarkus-quickstarts/blob/master/.github/workflows/native-build-development.yml#L28

**Comment by maxandersen** [comment]
Its been there since early days - see https://github.com/maxandersen/jbang#docker--github-action-docker and https://github.com/maxandersen/jbang-action

**Comment by rsvoboda** [comment]
Thanks, I haven't see it in action (e.g. Quarkus Quickstarts) so I thought it's not available
